#!/bin/bash
# Configure Blender as an iOS arm64 Python module (bpy.cpython-314-iphoneos / bin/bpy/__init__.so).
# Resumable source-of-truth for the OfflinAi Blender port. See PLAN.md.
set -e
cd "$(dirname "$0")"
export DEVELOPER_DIR=/Volumes/D/Xcode.app/Contents/Developer TMPDIR=/Volumes/D/tmp
PREFIX="$PWD/deps-install"
PYROOT=/Volumes/D/OfflinAi/Frameworks/Python.xcframework/ios-arm64

# Clean configure (a stale cache keeps the macOS-forced sysroot/deployment).
rm -rf build/blender

cmake -S blender -B build/blender -G Ninja \
  -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=16.4 -DCMAKE_OSX_SYSROOT=iphoneos \
  -DCMAKE_FIND_ROOT_PATH="$PREFIX" -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
  -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DLIBDIR="$PREFIX" \
  -DCMAKE_HAVE_LIBC_PTHREAD=1 -DTHREADS_PREFER_PTHREAD_FLAG=OFF \
  -DHOST_TOOLS_DIR="$PWD/build/host-tools" \
  -DWITH_PYTHON=ON -DWITH_PYTHON_MODULE=ON -DWITH_PYTHON_INSTALL=OFF -DPYTHON_VERSION=3.14 \
  -DPYTHON_INCLUDE_DIR="$PYROOT/include/python3.14" -DPYTHON_INCLUDE_CONFIG_DIR="$PYROOT/include/python3.14" \
  -DPYTHON_LIBRARY="$PYROOT/lib/libpython3.14.dylib" -DPYTHON_LIBPATH="$PYROOT/lib" \
  -DFREETYPE_INCLUDE_DIRS="$PREFIX/include/freetype2" -DFREETYPE_LIBRARY="$PREFIX/lib/libfreetype.a" \
  -DWITH_HEADLESS=ON -DWITH_CYCLES=ON -DWITH_CYCLES_DEVICE_METAL=ON -DWITH_GPU_BACKEND=none -DWITH_METAL_BACKEND=OFF \
  -DWITH_VULKAN_BACKEND=OFF -DWITH_OPENGL=OFF \
  -DWITH_BLENDER_THUMBNAILER=OFF \
  `# macOS-only QuickLook .appex; pulls in AppKit/NSImage which isn't on iOS` \
  -DWITH_OPENIMAGEIO=ON -DWITH_OPENCOLORIO=ON -DWITH_IMAGE_OPENEXR=ON -DWITH_TBB=ON \
  -DWITH_CYCLES_OSL=OFF \
  -DWITH_RUBBERBAND=OFF -DWITH_LIBMV=OFF \
  -DWITH_TRACY=OFF \
  -DWITH_USD=OFF -DWITH_HYDRA=OFF -DWITH_MATERIALX=OFF \
  \
  -DWITH_CODEC_FFMPEG=ON -DWITH_CODEC_SNDFILE=OFF -DWITH_JACK=OFF \
  -DWITH_PULSEAUDIO=OFF -DWITH_COREAUDIO=OFF -DWITH_OPENAL=OFF -DWITH_SDL=OFF -DWITH_AUDASPACE=OFF \
  -DWITH_INPUT_NDOF=OFF -DWITH_XR_OPENXR=OFF -DWITH_BOOST=OFF \
  -DWITH_FRIBIDI=OFF -DWITH_INTERNATIONAL=OFF \
  -DWITH_BUILDINFO=OFF \
  -DWITH_IMAGE_CINEON=ON \
  \
  "$@"

echo "=== configure exit: $? ==="
